/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import apstraktno.AbstractJDialog;
import domen.Artikal;
import domen.OpstiDomenskiObjekat;
import gui.komponente.ModelTabeleArtikli;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author SOLUNAC
 */
public class FmPretragaArtikala extends AbstractJDialog {

    /**
     * Creates new form FmPretragaArtikala
     */
    public FmPretragaArtikala(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kontroler.KontrolerKlijent.getInstance().setFmPretrazivanjeArtikala(this);
        popuniTabeluSaSvimArtiklima();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtKriterijum = new javax.swing.JTextField();
        jbtnPretrazi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblArtikli = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Unesite kriterijum pretrage:");

        jbtnPretrazi.setText("Pretraži");
        jbtnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretraziActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("(id artikla/naziv artikla)");

        jtblArtikli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblArtikli);

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnDetalji))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPretrazi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPretrazi))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnDetalji)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretraziActionPerformed
        // TODO add your handling code here:
        try {
            String kriterijum = jtxtKriterijum.getText().trim();
            kontroler.KontrolerKlijent.getInstance().setKriterijumPretrage(kriterijum);
            if (kriterijum.isEmpty()) {
                popuniTabeluSaSvimArtiklima();
            } else {
                List<OpstiDomenskiObjekat> lista = kontroler.KontrolerKlijent.getInstance().pretraziArtikle(kriterijum);
                if (!lista.isEmpty()) {
                    postaviModelTabele(lista);
                    prikaziPorukuObavestenja("Sistem je našao artikle po zadatoj vrednosti!");
                } else {
                    postaviModelTabele(new ArrayList<OpstiDomenskiObjekat>());
                    prikaziPorukuGreske("Sistem ne može da nađe artikle po zadatoj vrednosti!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnPretraziActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        // TODO add your handling code here:
        preuzmiPodatkeSelektovanogArtikla(util.Util.SK_PRIKAZ);
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnPretrazi;
    private javax.swing.JTable jtblArtikli;
    private javax.swing.JTextField jtxtKriterijum;
    // End of variables declaration//GEN-END:variables
    
    private void popuniTabeluSaSvimArtiklima() {
        try {
            List<OpstiDomenskiObjekat> lista = kontroler.KontrolerKlijent.getInstance().vratiListuArtikala();
            postaviModelTabele(lista);
        } catch (Exception e) {
            prikaziPorukuGreske("Došlo je do greške prilikom učitavanja artikala!");
        }
    }

    private void postaviModelTabele(List<OpstiDomenskiObjekat> lista) {
        jtblArtikli.setModel(new ModelTabeleArtikli(lista));
    }

    private void prikaziPorukuGreske(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Greška!", JOptionPane.ERROR_MESSAGE);
    }

    private void prikaziPorukuObavestenja(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Obaveštenje!", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void osvezi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void preuzmiPodatkeSelektovanogArtikla(int sk) {
        int red = jtblArtikli.getSelectedRow();
        if (red != -1) {
            try {
                Artikal izabraniArtikal = ((ModelTabeleArtikli) jtblArtikli.getModel()).vratiArtikal(red);
                List<OpstiDomenskiObjekat> lista = kontroler.KontrolerKlijent.getInstance().pretraziArtikle(izabraniArtikal.getArtikalID() + "");
                if (!lista.isEmpty()) {
                    prikaziPorukuObavestenja("Sistem je našao artikle po zadatoj vrednosti!");
                    Artikal artikalSaPodacima = (Artikal) lista.get(0);
                    kontroler.KontrolerKlijent.getInstance().setSelektovanArtikal(artikalSaPodacima);
                    kontroler.KontrolerKlijent.getInstance().setAktivan_sk(sk);
                    new FmUnosArtikla(null, true).setVisible(true);
                } else {
                    prikaziPorukuGreske("Sistem ne može da nađe artikal po zadatoj vrednosti!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            prikaziPorukuGreske("Niste selektovali nijedan artikal!");
        }
    }
}
