/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Artikal;
import domen.OpstiDomenskiObjekat;
import domen.TipArtikla;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SOLUNAC
 */
public class FmUnosArtikla extends javax.swing.JDialog {

    public boolean daLiJeKreiran = false;
    
    /**
     * Creates new form FmUnosArtikla
     */
    public FmUnosArtikla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormuPremaSK();
        popuniComboBoxove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtArtikalID = new javax.swing.JTextField();
        jbtnKreirajArtikal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtCena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcmbTipArtikla = new javax.swing.JComboBox<>();
        jbtnOdustani = new javax.swing.JButton();
        jbtnSacuvajArtikal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaOpis = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jtxtJedinicaMere = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Artikal ID:");

        jtxtArtikalID.setEditable(false);

        jbtnKreirajArtikal.setText("Kreiraj artikal");
        jbtnKreirajArtikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajArtikalActionPerformed(evt);
            }
        });

        jLabel2.setText("Naziv:*");

        jLabel3.setText("Cena:*");

        jLabel4.setText("Opis:");

        jLabel5.setText("Tip artikla:");

        jcmbTipArtikla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnOdustani.setText("Odustani");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jbtnSacuvajArtikal.setText("Sačuvaj artikal");
        jbtnSacuvajArtikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajArtikalActionPerformed(evt);
            }
        });

        jtxtaOpis.setColumns(20);
        jtxtaOpis.setRows(5);
        jScrollPane1.setViewportView(jtxtaOpis);

        jLabel6.setText("Jedinica mere:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSacuvajArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jbtnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addComponent(jLabel3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtArtikalID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnKreirajArtikal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCena, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcmbTipArtikla, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtJedinicaMere))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtArtikalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnKreirajArtikal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtJedinicaMere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbTipArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOdustani)
                    .addComponent(jbtnSacuvajArtikal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajArtikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajArtikalActionPerformed
        // TODO add your handling code here:
        try {
            Artikal artikal = kontroler.KontrolerKlijent.getInstance().kreirajArtikal();
            prikaziNoviArtikal(artikal);
            srediFormuArtikalJeKreiran();
            daLiJeKreiran = true;
            prikaziPorukuObavestenja("Sistem je kreirao artikal!");
        } catch (Exception e) {
            e.printStackTrace();
            prikaziPorukuGreske("Sistem ne može da kreira artikal!");
        }
    }//GEN-LAST:event_jbtnKreirajArtikalActionPerformed

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
        // TODO add your handling code here:
        if (daLiJeKreiran) {
            try {
                kontroler.KontrolerKlijent.getInstance().obrisiArtikal(jtxtArtikalID.getText() + "");
                daLiJeKreiran = false;
                srediFormuArtikalNijeKreiran();
                obrisiPodatkeIzPolja();
            } catch (Exception e) {
                prikaziPorukuGreske("Greška prilikom brisanja kreiranog artikla!");
            }
        }
    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    private void jbtnSacuvajArtikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajArtikalActionPerformed
        // TODO add your handling code here:
        try {
            double cena;
            int artikalID = Integer.parseInt(jtxtArtikalID.getText().trim());
            String naziv = jtxtNaziv.getText().trim();
            String opis = jtxtaOpis.getText().trim();
            String jedinicaMere = jtxtJedinicaMere.getText().trim();
            TipArtikla tipArtikla = (TipArtikla) jcmbTipArtikla.getSelectedItem();

            if (naziv == null || naziv.isEmpty()) {

                prikaziPorukuGreske("Niste uneli naziv artikla!");
                return;
            }

            try {
                cena = Double.parseDouble(jtxtCena.getText().trim());
                if (!(cena > 0)) {
                    prikaziPorukuGreske("Niste ispravno uneli cenu!");
                    return;
                }
            } catch (Exception e) {
                prikaziPorukuGreske("Niste uneli cenu!");
                return;
            }

            Artikal artikal = new Artikal(artikalID, naziv, cena, opis, jedinicaMere, tipArtikla);

            if (kontroler.KontrolerKlijent.getInstance().getAktivan_sk() == util.Util.SK_UNOS) {
                kontroler.KontrolerKlijent.getInstance().zapamtiArtikal(artikal);
                prikaziPorukuObavestenja("Ssitem je sačuvao artikal!");
                srediFormuArtikalNijeKreiran();
                obrisiPodatkeIzPolja();
            }
            

        } catch (Exception ex) {
            if (ex.getMessage() != null && ex.getMessage().equals(util.Util.VEC_POSTOJI_PORUKA)) {
                prikaziPorukuGreske("Već je unet ovakav artikal!");
                return;
            }
            ex.printStackTrace();
            prikaziPorukuGreske("Sistem ne može da zapamti artikal!");
        }
    }//GEN-LAST:event_jbtnSacuvajArtikalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (daLiJeKreiran) {
            try {
                kontroler.KontrolerKlijent.getInstance().obrisiArtikal(jtxtArtikalID.getText() + "");
            } catch (Exception e) {
                prikaziPorukuGreske("Greška prilikom brisanja kreiranog artikla!");
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    private void srediFormuPremaSK() {
        int aktivan = kontroler.KontrolerKlijent.getInstance().getAktivan_sk();
        if (aktivan == util.Util.SK_UNOS) {
            srediFormuArtikalNijeKreiran();
            this.setTitle("Unos podataka artikla");

        }
        
        if(aktivan == util.Util.SK_PRIKAZ) {
           jtxtArtikalID.setEditable(false);
           jtxtNaziv.setEditable(false);
           jtxtCena.setEditable(false);
           jtxtaOpis.setEditable(false);
           jtxtJedinicaMere.setEditable(false);
           jbtnKreirajArtikal.setEnabled(false);
           jbtnOdustani.setEnabled(false);
           jbtnSacuvajArtikal.setEnabled(false);
           jcmbTipArtikla.setEditable(false);
           prikaziPodatkeArtikla(kontroler.KontrolerKlijent.getInstance().getSelektovanArtikal());
           this.setTitle("Prikaz podataka artikla");
        }
    }

    private void popuniComboBoxove() {
        try {
            List<OpstiDomenskiObjekat> lista1 = kontroler.KontrolerKlijent.getInstance().vratiListuTipovaArtikala();
            popuniComboTipoviArtikla(lista1);
        } catch (Exception e) {
            prikaziPorukuGreske("Doslo je do problema prilikom popunjavanja combo boxova!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnKreirajArtikal;
    private javax.swing.JButton jbtnOdustani;
    private javax.swing.JButton jbtnSacuvajArtikal;
    private javax.swing.JComboBox<String> jcmbTipArtikla;
    private javax.swing.JTextField jtxtArtikalID;
    private javax.swing.JTextField jtxtCena;
    private javax.swing.JTextField jtxtJedinicaMere;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextArea jtxtaOpis;
    // End of variables declaration//GEN-END:variables
    
    private void prikaziPorukuGreske(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Greška!", JOptionPane.ERROR_MESSAGE);
    } 

    private void srediFormuArtikalNijeKreiran() {
        daLiJeKreiran = false;
        jtxtNaziv.setEnabled(false);
        jtxtCena.setEnabled(false);
        jtxtaOpis.setEnabled(false);
        jtxtJedinicaMere.setEnabled(false);
        jcmbTipArtikla.setEnabled(false);
        jbtnOdustani.setEnabled(false);
        jbtnSacuvajArtikal.setEnabled(false);
        jbtnKreirajArtikal.setEnabled(true);

    }

    private void prikaziNoviArtikal(Artikal artikal) {
        jtxtArtikalID.setText(artikal.getArtikalID() + "");
    }

    private void srediFormuArtikalJeKreiran() {
        jbtnKreirajArtikal.setEnabled(false);
        jtxtNaziv.setEnabled(true);
        jtxtCena.setEnabled(true);
        jtxtaOpis.setEnabled(true);
        jtxtJedinicaMere.setEnabled(true);
        jcmbTipArtikla.setEnabled(true);
        jbtnOdustani.setEnabled(true);
        jbtnSacuvajArtikal.setEnabled(true);

    }

    private void prikaziPorukuObavestenja(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Obaveštenje!", JOptionPane.INFORMATION_MESSAGE);
    }

    private void popuniComboTipoviArtikla(List<OpstiDomenskiObjekat> lista1) {
        jcmbTipArtikla.removeAllItems();
        jcmbTipArtikla.setModel(new DefaultComboBoxModel(lista1.toArray()));
    }

    private void obrisiPodatkeIzPolja() {
        jtxtNaziv.setText("");
        jtxtCena.setText("");
        jtxtaOpis.setText("");
        jtxtJedinicaMere.setText("");
        jcmbTipArtikla.setSelectedIndex(0);
    }

    private void prikaziPodatkeArtikla(Artikal selektovanArtikal) {
        jtxtArtikalID.setText(selektovanArtikal.getArtikalID() + "");
        jtxtNaziv.setText(selektovanArtikal.getNaziv());
        jtxtCena.setText(selektovanArtikal.getCena() + "");
        jtxtaOpis.setText(selektovanArtikal.getOpis());
        jtxtJedinicaMere.setText(selektovanArtikal.getJedinicaMere());
        jcmbTipArtikla.setSelectedItem(selektovanArtikal.getTipArtikla());
    }

}
