/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import apstraktno.AbstractJDialog;
import domen.Kupac;
import domen.OpstiDomenskiObjekat;
import domen.Racun;
import domen.Radnik;
import gui.komponente.ModelTabeleStavkeRacuna;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author SOLUNAC
 */
public class FmUnosRacuna extends AbstractJDialog {

    private JComboBox jcmbArtikli;
    private boolean daLiJeKreiran = false;
    
    /**
     * Creates new form FmUnosKupca
     */
    public FmUnosRacuna(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kontroler.KontrolerKlijent.getInstance().setFmUnosRacuna(this);
        srediFormuInicijalno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtRacunID = new javax.swing.JTextField();
        jtxtDatum = new javax.swing.JTextField();
        jtxtUkupnaVrednost = new javax.swing.JTextField();
        jbtnKreirajRacun = new javax.swing.JButton();
        jcmbKupac = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStavkeRacuna = new javax.swing.JTable();
        jbtnOdustani = new javax.swing.JButton();
        jbtnSacuvajRacun = new javax.swing.JButton();
        jbtnDodajStavkuRacuna = new javax.swing.JButton();
        jbtnObrisiStavkuRacuna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o računu"));

        jLabel1.setText("Račun ID:");

        jLabel2.setText("Datum:");

        jLabel3.setText("Kupac:");

        jLabel4.setText("Ukupna vrednost:");

        jtxtRacunID.setEditable(false);
        jtxtRacunID.setBackground(new java.awt.Color(240, 240, 240));

        jbtnKreirajRacun.setText("Kreiraj račun");
        jbtnKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajRacunActionPerformed(evt);
            }
        });

        jcmbKupac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtRacunID)
                    .addComponent(jtxtDatum)
                    .addComponent(jtxtUkupnaVrednost)
                    .addComponent(jcmbKupac, 0, 229, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jbtnKreirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnKreirajRacun))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtUkupnaVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke računa"));

        jtblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblStavkeRacuna);

        jbtnOdustani.setText("Odustani");
        jbtnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOdustaniActionPerformed(evt);
            }
        });

        jbtnSacuvajRacun.setText("Sačuvaj račun");
        jbtnSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajRacunActionPerformed(evt);
            }
        });

        jbtnDodajStavkuRacuna.setText("Dodaj stavku računa");
        jbtnDodajStavkuRacuna.setToolTipText("");
        jbtnDodajStavkuRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuRacunaActionPerformed(evt);
            }
        });

        jbtnObrisiStavkuRacuna.setText("Obriši stavku računa");
        jbtnObrisiStavkuRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuRacunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbtnDodajStavkuRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnObrisiStavkuRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSacuvajRacun)
                .addGap(28, 28, 28)
                .addComponent(jbtnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajStavkuRacuna)
                    .addComponent(jbtnObrisiStavkuRacuna))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvajRacun)
                    .addComponent(jbtnOdustani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajRacunActionPerformed
        // TODO add your handling code here:
        try {
            Racun racun = kontroler.KontrolerKlijent.getInstance().kreirajRacun();
            daLiJeKreiran = true;
            prikaziNoviRacun(racun);
            postaviModelTabele(racun);
            srediFormuRacunJeKreiran();
            prikaziPorukuObavestenja("Sistem je kreirao račun");

        } catch (Exception e) {
            e.printStackTrace();
            prikaziPorukuGreske("Sistem ne može da kreira račun!");
        }
    }//GEN-LAST:event_jbtnKreirajRacunActionPerformed

    private void jbtnObrisiStavkuRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuRacunaActionPerformed
        // TODO add your handling code here:
        boolean daLiImaStavki = ((ModelTabeleStavkeRacuna) jtblStavkeRacuna.getModel()).proveriBrojStavki();
        if (daLiImaStavki) {
            int red = jtblStavkeRacuna.getSelectedRow();
            if (red != -1) {
                ((ModelTabeleStavkeRacuna) jtblStavkeRacuna.getModel()).obrisiStavkuRacuna(red);
                jtxtUkupnaVrednost.setText(((ModelTabeleStavkeRacuna) jtblStavkeRacuna.getModel()).izracunajUkupnuVrednost() + "");
            } else {
                prikaziPorukuGreske("Niste obeležili ni jednu stavku za brisanje!");
            }
        } else {
            prikaziPorukuGreske("Račun nema ni jednu stavku!");
        }
    }//GEN-LAST:event_jbtnObrisiStavkuRacunaActionPerformed

    private void jbtnDodajStavkuRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuRacunaActionPerformed
        // TODO add your handling code here:
        ((ModelTabeleStavkeRacuna) jtblStavkeRacuna.getModel()).dodajStavkuRacuna();
    }//GEN-LAST:event_jbtnDodajStavkuRacunaActionPerformed

    private void jbtnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajRacunActionPerformed
        // TODO add your handling code here:
        try {
            Racun racun = ((ModelTabeleStavkeRacuna) jtblStavkeRacuna.getModel()).getRacun();
            Radnik radnik = kontroler.KontrolerKlijent.getInstance().vratiUlogovanogRadnika();
            Kupac kupac = (Kupac) jcmbKupac.getSelectedItem();
            racun.setRadnikID(radnik);
            racun.setKupacID(kupac);
            kontroler.KontrolerKlijent.getInstance().zapamtiRacun(racun);
            srediFormuRacunNijeKreiran();
            obrisiPodatkeIzPolja();
            prikaziPorukuObavestenja("Sistem je zapamtio račun");

        } catch (Exception e) {
            e.printStackTrace();
            prikaziPorukuGreske("Sistem ne može da zapamti račun!");
        }
    }//GEN-LAST:event_jbtnSacuvajRacunActionPerformed

    private void jbtnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOdustaniActionPerformed
        // TODO add your handling code here:
        try {
            kontroler.KontrolerKlijent.getInstance().obrisiRacun(jtxtRacunID.getText() + "");
            daLiJeKreiran = false;
            srediFormuRacunNijeKreiran();
            obrisiPodatkeIzPolja();

        } catch (Exception e) {
            prikaziPorukuGreske("Došlo je do greške prilikom brisanja kreiranog računa!");
        }
    }//GEN-LAST:event_jbtnOdustaniActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (daLiJeKreiran) {
            try {
                kontroler.KontrolerKlijent.getInstance().obrisiRacun(jtxtRacunID.getText() + "");
            } catch (Exception e) {
                prikaziPorukuGreske("Došlo je do greške prilikom brisanja kreiranog računa!");
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajStavkuRacuna;
    private javax.swing.JButton jbtnKreirajRacun;
    private javax.swing.JButton jbtnObrisiStavkuRacuna;
    private javax.swing.JButton jbtnOdustani;
    private javax.swing.JButton jbtnSacuvajRacun;
    private javax.swing.JComboBox<String> jcmbKupac;
    private javax.swing.JTable jtblStavkeRacuna;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtRacunID;
    private javax.swing.JTextField jtxtUkupnaVrednost;
    // End of variables declaration//GEN-END:variables

    private void popuniComboKupci(List<OpstiDomenskiObjekat> lista) {
        jcmbKupac.removeAllItems();
        jcmbKupac.setModel(new DefaultComboBoxModel(lista.toArray()));
    }

    private void prikaziPorukuGreske(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Greška!", JOptionPane.ERROR_MESSAGE);
    }

    private void srediFormuPremaSK() {
        int aktivan = kontroler.KontrolerKlijent.getInstance().getAktivan_sk();
        if (aktivan == util.Util.SK_UNOS) {
            srediFormuRacunNijeKreiran();
            this.setTitle("Unos podataka računa");
        }

        if (aktivan == util.Util.SK_PRIKAZ) {
            jtxtRacunID.setEditable(false);
            jtxtDatum.setEditable(false);
            jtxtUkupnaVrednost.setEditable(false);
            jcmbKupac.setEnabled(false);
            jbtnKreirajRacun.setVisible(false);
            jbtnOdustani.setVisible(false);
            jbtnSacuvajRacun.setVisible(false);
            jbtnDodajStavkuRacuna.setVisible(false);
            jbtnObrisiStavkuRacuna.setVisible(false);
            jtblStavkeRacuna.setEnabled(false);
            prikaziPodatkeRacuna(kontroler.KontrolerKlijent.getInstance().getSelektovanRacun());
            this.setTitle("Prikaz podataka računa");

        }
    }

    private void srediFormuRacunNijeKreiran() {
        daLiJeKreiran = false;
        jtxtDatum.setEnabled(false);
        jtxtUkupnaVrednost.setEnabled(false);
        jcmbKupac.setEnabled(false);
        jtblStavkeRacuna.setEnabled(false);
        jbtnDodajStavkuRacuna.setEnabled(false);
        jbtnObrisiStavkuRacuna.setEnabled(false);
        jbtnSacuvajRacun.setEnabled(false);
        jbtnOdustani.setEnabled(false);
        jbtnKreirajRacun.setEnabled(true);

    }

    private void prikaziNoviRacun(Racun rac) {
        jtxtRacunID.setText(rac.getRacunID() + "");
        jtxtDatum.setText(new SimpleDateFormat("dd.MM.yyyy").format(rac.getDatum()));
        jtxtUkupnaVrednost.setText(0 + "");
    }

    private void prikaziPorukuObavestenja(String poruka) {
        JOptionPane.showMessageDialog(this, poruka, "Obaveštenje!", JOptionPane.INFORMATION_MESSAGE);
    }

    private void srediFormuRacunJeKreiran() {
        jtxtDatum.setEnabled(true);
        jtxtUkupnaVrednost.setEnabled(true);
        jcmbKupac.setEnabled(true);
        jtblStavkeRacuna.setEnabled(true);
        jbtnDodajStavkuRacuna.setEnabled(true);
        jbtnObrisiStavkuRacuna.setEnabled(true);
        jbtnSacuvajRacun.setEnabled(true);
        jbtnOdustani.setEnabled(true);
        jbtnKreirajRacun.setEnabled(false);
    }

    private void popuniComboArtikli(List<OpstiDomenskiObjekat> lista) {
        jcmbArtikli.removeAllItems();
        jcmbArtikli.setModel(new DefaultComboBoxModel(lista.toArray()));
    }

    private void postaviModelTabele(Racun racun) {
        jtblStavkeRacuna.setModel(new ModelTabeleStavkeRacuna(racun));

        TableColumnModel tcm = jtblStavkeRacuna.getColumnModel();
        TableColumn tc = tcm.getColumn(1);
        tc.setCellEditor(new DefaultCellEditor(jcmbArtikli));
    }

    private void obrisiPodatkeIzPolja() {
        jtxtDatum.setText("");
        jtxtUkupnaVrednost.setText("");
        jcmbKupac.setSelectedIndex(0);
        jtblStavkeRacuna.setModel(new ModelTabeleStavkeRacuna(new Racun()));
    }

    @Override
    public void osvezi() {
        double ukupnaVrednost = ((ModelTabeleStavkeRacuna) jtblStavkeRacuna.getModel()).izracunajUkupnuVrednost();
        jtxtUkupnaVrednost.setText(ukupnaVrednost + "");
    }

    private void srediFormuInicijalno() {
        try {
            List<OpstiDomenskiObjekat> lista = kontroler.KontrolerKlijent.getInstance().vratiListuKupaca();
            popuniComboKupci(lista);

            jcmbArtikli = new JComboBox();
            List<OpstiDomenskiObjekat> lista1 = kontroler.KontrolerKlijent.getInstance().vratiListuArtikala();
            popuniComboArtikli(lista1);
            postaviModelTabele(new Racun());
            srediFormuPremaSK();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void prikaziPodatkeRacuna(Racun r) {
        jtxtRacunID.setText(r.getRacunID() + "");
        jtxtDatum.setText(new SimpleDateFormat("dd.MM.yyyy").format(r.getDatum()));
        jtxtUkupnaVrednost.setText(r.getVrednost() + "");
        jcmbKupac.setSelectedItem(r.getKupacID());
        postaviModelTabele(r);
    }
}
