/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import gui.komponente.ModelTabeleKorisnici;
import java.awt.Color;
import javax.swing.JTable;
import kontroler.KontrolerServer;

/**
 *
 * @author SOLUNAC
 */
public class FmServer extends javax.swing.JFrame {

    /**
     * Creates new form FmServer
     */
    public FmServer() {
        initComponents();
        srediPanele();
        popuniTabeluKorisnici();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlStatus = new javax.swing.JPanel();
        jlblSeverStatus = new javax.swing.JLabel();
        jbtnPokretanjeServera = new javax.swing.JButton();
        jpnlKorisnici = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKorisnici = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Status servera"));

        jlblSeverStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblSeverStatus.setForeground(new java.awt.Color(255, 0, 51));
        jlblSeverStatus.setText("Server nije pokrenut!");

        jbtnPokretanjeServera.setText("Pokreni server");
        jbtnPokretanjeServera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPokretanjeServeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlStatusLayout = new javax.swing.GroupLayout(jpnlStatus);
        jpnlStatus.setLayout(jpnlStatusLayout);
        jpnlStatusLayout.setHorizontalGroup(
            jpnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlStatusLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jlblSeverStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPokretanjeServera, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jpnlStatusLayout.setVerticalGroup(
            jpnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlStatusLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jpnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSeverStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPokretanjeServera))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jpnlKorisnici.setBorder(javax.swing.BorderFactory.createTitledBorder("Korisnici"));

        jtblKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblKorisnici);

        javax.swing.GroupLayout jpnlKorisniciLayout = new javax.swing.GroupLayout(jpnlKorisnici);
        jpnlKorisnici.setLayout(jpnlKorisniciLayout);
        jpnlKorisniciLayout.setHorizontalGroup(
            jpnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlKorisniciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpnlKorisniciLayout.setVerticalGroup(
            jpnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlKorisniciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnlKorisnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlKorisnici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPokretanjeServeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPokretanjeServeraActionPerformed
        // TODO add your handling code here:
        KontrolerServer.getInstance().pokreniServer(this);
        jlblSeverStatus.setText("Server je pokrenut!");
        jlblSeverStatus.setForeground(Color.green);
        KontrolerServer.getInstance().setForma(this);
    }//GEN-LAST:event_jbtnPokretanjeServeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPokretanjeServera;
    private javax.swing.JLabel jlblSeverStatus;
    private javax.swing.JPanel jpnlKorisnici;
    private javax.swing.JPanel jpnlStatus;
    private javax.swing.JTable jtblKorisnici;
    // End of variables declaration//GEN-END:variables

    private void srediPanele(){
        jpnlStatus.setVisible(true);
        jpnlKorisnici.setVisible(true);
    }
    
    public JTable getJtblKorisnici(){
        return jtblKorisnici;
    }
    
    private void popuniTabeluKorisnici(){
        jtblKorisnici.setModel(new ModelTabeleKorisnici());
    }

}

